name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

    # ⏰ WakaTime plugin
      # Display your wakatime metrics
      - name: ⏰ WakaTime plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: e7f549a2-7433-4fee-8ff2-641a6fb61ca9 # ${{ secrets.WAKATIME_TOKEN }}
          use_mocked_data: no            # ⚠️ Using mocked data because I don't really use WakaTime
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}

      # Display isometric calendar (180 days)
      - name: 📅 Isocalendar plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
